
-- ALL INDAI INVESTOR SEARCH

SELECT INVESTOR_NAME,INV_CODE, A.ADDRESS1, A.ADDRESS2, C.CITY_NAME, B.BRANCH_NAME, A.PHONE, E.RM_NAME, CM.GUEST_CD, A.PAN, T.CLIENT_CODE 
FROM BRANCH_MASTER B, EMPLOYEE_MASTER E, INVESTOR_MASTER A, CITY_MASTER C, CLIENT_TEST T, CLIENT_MASTER CM 
WHERE CM.CLIENT_CODE=A.SOURCE_ID AND T.CLIENT_CODEKYC=A.INV_CODE AND A.CITY_ID=C.CITY_ID(+) AND E.SOURCE=B.BRANCH_CODE 
AND A.RM_CODE=E.RM_CODE AND INVESTOR_NAME IS NOT NULL;



SELECT INVESTOR_NAME,INV_CODE, A.ADDRESS1, A.ADDRESS2, C.CITY_NAME, B.BRANCH_NAME, A.PHONE, E.RM_NAME, T.GUEST_CODE, A.PAN, T.CLIENT_CODE 
FROM BRANCH_MASTER B,EMPLOYEE_MASTER E,INVESTOR_MASTER A,CITY_MASTER C,CLIENT_TEST T  
WHERE T.CLIENT_CODEKYC=A.INV_CODE AND A.CITY_ID=C.CITY_ID(+) AND E.SOURCE=B.BRANCH_CODE AND A.RM_CODE=E.RM_CODE 
AND INVESTOR_NAME IS NOT NULL;

 Select CLIENT_name,CLIENT_CODE,a.address1,a.address2,C.CITY_NAME,b.Branch_name,DECODE(a.client_type,'RELIGARE','RELIGARE',NULL),e.rm_name 
 FROM Branch_master b,EMPLOYEE_MASTER E,CLIENT_master a,City_master c where  E.source=b.branch_code AND a.RM_CODE=E.RM_CODE 
 AND a.city_id=C.city_id(+) and CLIENT_name IS NOT NULL AND b.branch_code<>10010226 AND b.branch_code<>10070257
 and B.BRANCH_CODE in (SELECT BRANCH_ID FROM USERDETAILS_JI WHERE USERDETAILS_JI.LOGIN_ID = '121397' AND USERDETAILS_JI.ROLE_ID = '212');
 
 SELECT DATAFILTER FROM USERDETAILS_JI WHERE USERDETAILS_JI.LOGIN_ID = '121397' AND USERDETAILS_JI.ROLE_ID = '212';
 
-- FILTER SERACH MF-CLIENT

Select CLIENT_name,CLIENT_CODE,a.address1,a.address2,C.CITY_NAME,b.Branch_name,DECODE(a.client_type,'RELIGARE','RELIGARE',NULL),e.rm_name FROM Branch_master b,EMPLOYEE_MASTER E,CLIENT_master a,City_master c where E.source=b.branch_code AND a.RM_CODE=E.RM_CODE AND a.city_id=C.city_id(+) and CLIENT_name IS NOT NULL and upper(a.CLIENT_NAME) like '%ARJUN%' and B.BRANCH_CODE='10010042' --> NAME: ARJUN





