CREATE OR REPLACE FUNCTION WEALTHMAKER.IS_FAMILY_HEAD(PINV_CODE VARCHAR2) RETURN NUMBER IS
VCLIENT_NAME CLIENT_TEST.CLIENT_NAME%TYPE;
VSOURCE_CODE CLIENT_TEST.SOURCE_CODE%TYPE;
VCNT         NUMBER:=0; 
BEGIN
     BEGIN
          SELECT CLIENT_NAME,SOURCE_CODE INTO VCLIENT_NAME,VSOURCE_CODE FROM CLIENT_TEST WHERE CLIENT_CODEKYC=PINV_CODE AND ROWNUM=1;
     EXCEPTION WHEN OTHERS THEN
          VCLIENT_NAME:=NULL;
          VSOURCE_CODE:=NULL;
          VCNT:=0;  
     END;       
     
     IF VCLIENT_NAME IS NOT NULL THEN
           BEGIN 
               SELECT COUNT(*) INTO VCNT FROM CLIENT_MASTER T  WHERE CLIENT_CODE = VSOURCE_CODE
               AND EXISTS
                      (SELECT SOURCE_CODE
                         FROM CLIENT_TEST T1
                        WHERE     T1.CLIENT_CODE = T1.MAIN_CODE
                              AND T1.SOURCE_CODE = T.CLIENT_CODE
                              AND STR_MATCH_TEXT (UPPER (VCLIENT_NAME),UPPER (TRIM (T1.CLIENT_NAME))) = 1);
          EXCEPTION WHEN OTHERS THEN
            VCNT:=0;
          END;                      
     END IF;                     
     RETURN VCNT;                                      
END;
