DROP TABLE WEALTHMAKER.PSM_DAP_TEMP_DUE1_LAP CASCADE CONSTRAINTS;

CREATE TABLE WEALTHMAKER.PSM_DAP_TEMP_DUE1_LAP
(
  POLICY_NO      VARCHAR2(100 BYTE),
  COMPANY_CD     VARCHAR2(100 BYTE),
  DUE_DATE       VARCHAR2(100 BYTE),
  MON_NO         VARCHAR2(100 BYTE),
  YEAR_NO        VARCHAR2(100 BYTE),
  STATUS_CD      VARCHAR2(100 BYTE),
  DAYS_LAPSED    VARCHAR2(100 BYTE),
  LAST_PREM_AMT  VARCHAR2(100 BYTE),
  PAY_MODE       VARCHAR2(100 BYTE),
  SA_AMT         VARCHAR2(100 BYTE),
  CL_NAME        VARCHAR2(100 BYTE),
  IMPORT_DATE    VARCHAR2(100 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;
