DROP TABLE WEALTHMAKER.PSM_DAP_TEMP_PAID1 CASCADE CONSTRAINTS;

CREATE TABLE WEALTHMAKER.PSM_DAP_TEMP_PAID1
(
  POLICY_NO      VARCHAR2(100 BYTE),
  COMPANY_CD     VARCHAR2(100 BYTE),
  PREM_AMT       VARCHAR2(100 BYTE),
  PAID_DATE      VARCHAR2(100 BYTE),
  STATUS_CD      VARCHAR2(100 BYTE),
  NET_AMOUNT     VARCHAR2(100 BYTE),
  DUE_DATE       VARCHAR2(100 BYTE),
  NEXT_DUE_DATE  VARCHAR2(100 BYTE),
  PREM_FREQ      VARCHAR2(100 BYTE),
  PAY_MODE       VARCHAR2(100 BYTE),
  DOC            VARCHAR2(100 BYTE),
  PLAN_NAME      VARCHAR2(100 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;
