SELECT DISTINCT(P.POLICY_NO) AS POLICY_NO,
       MAX(A.PREM_AMT) AS MAX_AMT,
       DECODE(MAX(A.PREM_FREQ), 1, 'Y', 2, 'HY', 4, 'Q', 12, 'M') AS PREM_FREQ,
       MAX(A.NEXT_DUE_DT) AS NEXT_DUE_DT,
       MAX(A.COMPANY_CD) AS COMPANY_CD,
       R.REGION_NAME AS REGION_NAME,
       Z.ZONE_NAME AS ZONE_NAME,
       E.RM_NAME AS RM_NAME,
       B.BRANCH_NAME AS BRANCH_NAME,
       I.INVESTOR_NAME AS INVESTOR_NAME,
       I.ADDRESS1 AS ADDRESS1,
       I.ADDRESS2 AS ADDRESS2,
       C.CITY_NAME AS CITY_NAME,
       S.STATE_NAME AS STATE_NAME,
       I.MOBILE AS MOBILE,
       I.PHONE AS PHONE
FROM   BRANCH_MASTER B,
       ZONE_MASTER Z,
       POLICY_MAP_TEMP1 P,
       BAJAJ_AR_HEAD A,
       INVESTOR_MASTER I,
       EMPLOYEE_MASTER E,
       REGION_MASTER R,
       STATE_MASTER S,
       CITY_MASTER C
WHERE  A.FRESH_RENEWAL IN ('1', '5')
       AND I.CITY_ID = C.CITY_ID
       AND C.STATE_ID = S.STATE_ID
       AND E.PAYROLL_ID = TO_CHAR(A.EMP_NO)
       AND TRIMZERO(UPPER(TRIM(P.POLICY_NO))) = TRIMZERO(UPPER(TRIM(A.POLICY_NO)))
       AND A.CLIENT_CD = I.INV_CODE
       AND I.BRANCH_CODE = B.BRANCH_CODE
       AND B.REGION_ID = R.REGION_ID
       AND B.ZONE_ID = Z.ZONE_ID
       -- Optional filters applied based on conditions
       AND TRIM(UPPER(P.COMPANY_CD)) = UPPER(TRIM(A.COMPANY_CD))
       -- AND A.COMPANY_CD = '<CompanyCodeFromCombo>'
GROUP BY P.POLICY_NO,
         P.COMPANY_CD,
         B.BRANCH_NAME,
         R.REGION_NAME,
         Z.ZONE_NAME,
         I.INVESTOR_NAME,
         I.ADDRESS1,
         I.ADDRESS2,
         I.MOBILE,
         I.PHONE,
         E.RM_NAME,
         C.CITY_NAME,
         S.STATE_NAME
