CREATE OR REPLACE PROCEDURE WEALTHMAKER.PSM_LOG_REGION_LIST(
P_FOR        IN VARCHAR2,
P_BY         IN VARCHAR2,
P_BY_VALUE   IN VARCHAR2,
P_LOG_ID     IN VARCHAR2,
P_ROLE_ID    IN VARCHAR2,
P_CURSOR        OUT SYS_REFCURSOR

) AS
V_QUERY         VARCHAR2(4000);
BEGIN 

    V_QUERY := ' SELECT DISTINCT RM.REGION_NAME AS REGION_NAME, RM.REGION_ID AS REGION_CODE ';

    V_QUERY := V_QUERY|| ' FROM REGION_MASTER RM JOIN BRANCH_MASTER BM ON RM.REGION_ID = BM.REGION_ID ';
    V_QUERY := V_QUERY|| ' WHERE 1=1 ';
    V_QUERY := V_QUERY|| ' AND BM.BRANCH_CODE IN (SELECT BRANCH_ID FROM USERDETAILS_JI WHERE LOGIN_ID = '''||P_LOG_ID||''' AND ROLE_ID='''||P_ROLE_ID||''') ';

    IF P_FOR = 'MF_AR_MANUAL_RECO' THEN  
        V_QUERY := V_QUERY|| ' AND BM.CATEGORY_ID NOT IN (''1004'', ''1005'', ''1006'') ';
    END IF;
    
    IF P_BY = 'CHANNEL' AND P_BY_VALUE IS NOT NULL THEN
        V_QUERY := V_QUERY|| ' AND BM.BRANCH_TAR_CAT = '''||P_BY_VALUE||''' ';
    END IF; 
    
    V_QUERY := V_QUERY|| ' ORDER BY RM.REGION_NAME ';
    
    OPEN P_CURSOR FOR V_QUERY;
    --OPEN P_CURSOR FOR select V_QUERY from dual;
     
END;
/