CREATE OR REPLACE PROCEDURE WEALTHMAKER.PSM_MF_RECO_M_FIND_TRAN2 (
    P_TRANCODE     IN TRANSACTION_MF_TEMP1.TRAN_CODE%TYPE,
    O_DETAILS      OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN O_DETAILS FOR
        SELECT NVL(A.HO_TRAN_CODE, 0) AS HO_TRAN_CODE, B.BRANCH_NAME, A.AMOUNT
        FROM TRANSACTION_ST@MF.BAJAJCAPITAL A
        JOIN BRANCH_MASTER B ON A.BRANCH_CODE = B.BRANCH_CODE
        WHERE A.TRAN_CODE = P_TRANCODE;
END;
/