CREATE OR REPLACE PROCEDURE WEALTHMAKER.PSM_LOG_CHANNEL_LIST(
P_FOR        IN VARCHAR2,
P_BY         IN VARCHAR2,
P_BY_VALUE   IN VARCHAR2,
P_LOG_ID     IN VARCHAR2,
P_ROLE_ID    IN VARCHAR2,
P_CURSOR     OUT SYS_REFCURSOR

) IS

  V_QUERY    VARCHAR2(4000);
   
BEGIN 

    V_QUERY:= V_QUERY || ' SELECT ITEMNAME AS CHANNEL_NAME, ITEMSERIALNUMBER AS CHANNEL_CODE ';    
    V_QUERY:= V_QUERY || ' FROM FIXEDITEM ';
    V_QUERY:= V_QUERY || ' WHERE 1=1 ';
    
    IF P_FOR = 'MF_AR_MANUAL_RECO' THEN  
        V_QUERY:= V_QUERY || ' AND ITEMTYPE = ''26'' ';
    END IF;

    V_QUERY:= V_QUERY || ' ORDER BY ITEMNAME ';
    --AND BRANCH_CODE IN (SELECT BRANCH_ID FROM USERDETAILS_JI WHERE LOGIN_ID = P_LOG_ID AND ROLE_ID=P_ROLE_ID) 
    
    OPEN P_CURSOR FOR V_QUERY;
    --OPEN P_CURSOR FOR select V_QUERY from dual;


END;
/