CREATE OR REPLACE PROCEDURE WEALTHMAKER.PSM_SIP2_SET_REMARK (
    P_TR_CODE     IN VARCHAR2,
    P_REMARK      IN VARCHAR2,
    P_LOG_ID      IN VARCHAR2,
    P_ROLE_ID     IN VARCHAR2,
    P_CURSOR      OUT SYS_REFCURSOR
) AS
    V_ERROR_MSG         VARCHAR2(4000);
BEGIN
    IF P_TR_CODE IS NULL OR P_REMARK IS NULL  THEN
        OPEN P_CURSOR FOR SELECT '⚠️ Please double click the record,you want to remark and renter remark' AS MESSAGE FROM DUAL;
        RETURN;
    END IF;

    SAVEPOINT START_TRANSACTION;
    
    UPDATE TRANSACTION_MF_TEMP1 SET REMARK_RECO = P_REMARK WHERE TRAN_CODE = P_TR_CODE;
    UPDATE TRANSACTION_MF_TEMP1 SET REMARK_RECO = P_REMARK WHERE BASE_TRAN_CODE = P_TR_CODE;

    OPEN P_CURSOR FOR
        SELECT 'SUCCESS: The record has been remarked sucessfully' AS MESSAGE
        FROM DUAL; 
    COMMIT;

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK TO START_TRANSACTION;
        V_ERROR_MSG := SQLERRM;
        OPEN P_CURSOR FOR 
        SELECT '❌ ERROR: ' || V_ERROR_MSG AS MESSAGE FROM DUAL;
END;
/