SELECT 
  DU.COMMON_ID, 
  CM.CLIENT_CODE, 
  IM.INV_CODE, 
  CT.CLIENT_CODE
FROM TB_DOC_UPLOAD DU
LEFT JOIN CLIENT_TEST CT ON DU.INV_CODE = CT.CLIENT_CODEKYC
LEFT JOIN CLIENT_MASTER CM ON CM.CLIENT_CODE = SUBSTR(CT.CLIENT_CODEKYC, 1, 8)
LEFT JOIN INVESTOR_MASTER IM ON SUBSTR(IM.INV_CODE, 1, 8) = CM.CLIENT_CODE
WHERE DU.VERIFICATION_FLAG = '1' 
  AND DU.REJECTION_STATUS = '0' 
  AND DU.TRAN_TYPE = 'AC' 
  AND DU.PUNCHING_FLAG = '0';