CREATE OR REPLACE PROCEDURE PSM_NPS_ECS_BULK_IMP(
    P_IMP_TYPE  IN VARCHAR2, -- ECS, NONECS,
    P_ZERO_COMM IN VARCHAR2,
    P_LOG_ID    IN VARCHAR2,
    P_ROLE_ID   IN VARCHAR2,
    P_OUT       OUT SYS_REFCURSOR
) AS

V_RETURN_MSG VARCHAR2(100);
V_COUNT1 NUMBER;
V_COUNT2 NUMBER;
BEGIN

    IF P_IMP_TYPE = 'NONECS' THEN
        -- all excel is inserted in PSM_NPS_NES_TBL_TEMP1
        -- proc to clean the temp table 'PSM_NPS_NES_TEMP_CLEAN
        -- func that containt fie name PSM_NPS_IMP_GET_COMP_TEXT'

        INSERT INTO NPS_NONECS_TBL_IMP_BK SELECT * FROM  NPS_NONECS_TBL_IMP;
        DELETE FROM  NPS_NONECS_TBL_IMP;

        INSERT INTO NPS_NONECS_TBL_IMP (REF_TRAN_CODE,TR_DATE,ECS_AMT,ECS_PERIOD,ECS_PAY_DT,ECS_TRAN_CODE,
        LOGGEDUSERID,TIMEST,MODIFY_USER,MODIFY_DATE,TPSL_TRANID,CONSUMER_CODE,IMPORT_DT)
        SELECT REF_TRAN_CODE, TO_DATE(TR_DATE, 'DD-MON-YYYY'), TO_NUMBER(ECS_AMT), ECS_PERIOD, TO_DATE(ECS_PAY_DT, 'DD-MON-YYYY'), ECS_TRAN_CODE,
        P_LOG_ID, TO_DATE(TIMEST, 'DD-MON-YYYY'), NULL, NULL, TPSL_TRANID, CONSUMER_CODE, TO_DATE(IMPORT_DT, 'DD-MON-YYYY') FROM PSM_NPS_NES_TBL_TEMP1;
    
        DELETE NPS_NONECS_TBL_IMP WHERE REF_TRAN_CODE IS NULL;
        V_COUNT1 := SQL%ROWCOUNT;
        V_RETURN_MSG := 'Total Records Inserted: ' || V_COUNT1;

    ELSIF P_IMP_TYPE = 'ECS' THEN
        -- all excel is inserted in PSM_NPS_ECS_TBL_TEMP1
        -- proc to clean the temp table 'PSM_NPS_ECS_TEMP_CLEAN'
        -- func that containt fie name PSM_NPS_IMP_GET_COMP_TEXT'

        INSERT INTO NPS_ECS_TBL_IMP_BK SELECT * FROM  NPS_ECS_TBL_IMP;
        DELETE FROM  NPS_ECS_TBL_IMP;



        INSERT INTO NPS_ECS_TBL_IMP (REF_TRAN_CODE,TR_DATE,ECS_AMT,ECS_PERIOD,ECS_PAY_DT,ECS_TRAN_CODE,LOGGEDUSERID,TIMEST,MODIFY_USER,MODIFY_DATE,TPSL_TRANID,CONSUMER_CODE,IMPORT_DT)
        SELECT 
            REF_TRAN_CODE, TO_DATE(TR_DATE, 'DD-MON-YYYY'), TO_NUMBER(ECS_AMT), ECS_PERIOD, TO_DATE(ECS_PAY_DT, 'DD-MON-YYYY'), ECS_TRAN_CODE,
            P_LOG_ID, TO_DATE(TIMEST, 'DD-MON-YYYY'), NULL, NULL, TPSL_TRANID, CONSUMER_CODE, TO_DATE(IMPORT_DT, 'DD-MON-YYYY') FROM PSM_NPS_NES_TBL_TEMP1;

        DELETE NPS_ECS_TBL_IMP WHERE REF_TRAN_CODE IS NULL;

        V_COUNT2 := SQL%ROWCOUNT;
        V_RETURN_MSG := 'Total Records Inserted: ' || V_COUNT2;

    END IF;

    OPEN P_OUT FOR 
        SELECT V_RETURN_MSG FROM DUAL;
        
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(-20001, 'Error in clean_and_update_nps_nonecs: ' || SQLERRM);
END;