CREATE OR REPLACE PROCEDURE WEALTHMAKER.PSM_AO_GETCITIESBYSTATE (
    P_STATE_ID IN NUMBER,
    P_CITIES_CURSOR OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN P_CITIES_CURSOR FOR
    SELECT CM.CITY_ID, CM.CITY_NAME
    FROM CITY_MASTER CM
    WHERE 
    CM.STATE_ID     =   P_STATE_ID AND 
    CM.CITY_ID          IS NOT NULL
    AND CM.STATE_ID     IS NOT NULL
    AND TRIM(CM.DEL_FLAG) IS NULL
    ORDER BY CM.CITY_NAME;
END PSM_AO_GETCITIESBYSTATE;
/
