DROP VIEW WEALTHMAKER.NPSTRANRECEIPT_VIEW;

/* Formatted on 16/06/2025 12:16:14 (QP5 v5.336) */
CREATE OR REPLACE FORCE VIEW WEALTHMAKER.NPSTRANRECEIPT_VIEW
(
    TRAN_CODE,
    TR_DATE,
    CLIENT_CODE,
    MUT_CODE,
    SCH_CODE,
    APP_NO,
    FOLIO_NO,
    TRAN_TYPE,
    REF_TRAN_CODE,
    AMOUNT,
    UNITS,
    RATE,
    APP_DATE,
    BRANCH_CODE,
    SOURCE_CODE,
    RE_INVT,
    NEW_FROM_BROK_STAT,
    NAV_DATE,
    PAYMENT_MODE,
    CHEQUE_DATE,
    CHEQUE_NO,
    BANK_NAME,
    BANK_BRANCH,
    BANK_AC_NO,
    ASR,
    ASA,
    BROKER_ID,
    BROK_CAL,
    INVESTOR_TYPE,
    SWITCH_SCHEME,
    SWITCH_FOLIO,
    INTER,
    SWITCH_TRANCODE,
    RMCODE,
    BILL_GEN,
    SYS_TRAN,
    MANUAL_ARNO,
    CHALLAN_FL,
    BUSINESS_RMCODE,
    TRAN_ID,
    LOGGEDUSERID,
    TIMEST,
    REMARK,
    FLAG,
    IMP_DATE,
    TRAN_UPDATE,
    BUSI_BRANCH_CODE,
    REG_DATE,
    MODIFY_USER,
    MODIFY_DATE,
    FAMILY_HEAD,
    FPF_DATE,
    FPL_DATE,
    CH_RECO,
    POSTED,
    REG_TRANTYPE,
    CROR_PLANNO,
    CROR_DATE,
    AUDIT_FPDATE,
    PLAN_TYPE,
    REG_SUBBROK,
    SEQ_NO,
    REG_TRAN_FLAG,
    AUM_FLAG,
    INV_NAME,
    PORTFOLIO_FLAG,
    DUP_FLAG,
    DUP_FLAG1,
    DUP_FLAG2,
    UNIQUE_ID,
    AUTOMAP_FLAG,
    FP_STATUS,
    MODIFY_TALISMA,
    TRAN_SRC,
    REMARKS_1,
    AMOUNT1,
    TRANCODE,
    AMT1,
    AMOUNT2,
    REG_CHARGE,
    SERVICETAX,
    TRAN_CHARGE,
    BCODE,
    BRANCH_NAME,
    REGION_ID,
    REGION_NAME,
    ZONE_ID,
    ZONE_NAME,
    NSDL_NO,
    OSCH_NAME,
    INVESTOR_NAME,
    RM_NAME,
    PAYROLL_ID,
    REQUEST_NAME,
    POPBRANCH,
    SUBBRANCH,
    INVOICE_NO
)
BEQUEATH DEFINER
AS
    SELECT T."TRAN_CODE",
           T."TR_DATE",
           T."CLIENT_CODE",
           T."MUT_CODE",
           T."SCH_CODE",
           T."APP_NO",
           T."FOLIO_NO",
           T."TRAN_TYPE",
           T."REF_TRAN_CODE",
           T."AMOUNT",
           T."UNITS",
           T."RATE",
           T."APP_DATE",
           T."BRANCH_CODE",
           T."SOURCE_CODE",
           T."RE_INVT",
           T."NEW_FROM_BROK_STAT",
           T."NAV_DATE",
           T."PAYMENT_MODE",
           T."CHEQUE_DATE",
           T."CHEQUE_NO",
           T."BANK_NAME",
           T."BANK_BRANCH",
           T."BANK_AC_NO",
           T."ASR",
           T."ASA",
           T."BROKER_ID",
           T."BROK_CAL",
           T."INVESTOR_TYPE",
           T."SWITCH_SCHEME",
           T."SWITCH_FOLIO",
           T."INTER",
           T."SWITCH_TRANCODE",
           T."RMCODE",
           T."BILL_GEN",
           T."SYS_TRAN",
           T."MANUAL_ARNO",
           T."CHALLAN_FL",
           T."BUSINESS_RMCODE",
           T."TRAN_ID",
           T."LOGGEDUSERID",
           T."TIMEST",
           T."REMARK",
           T."FLAG",
           T."IMP_DATE",
           T."TRAN_UPDATE",
           T."BUSI_BRANCH_CODE",
           T."REG_DATE",
           T."MODIFY_USER",
           T."MODIFY_DATE",
           T."FAMILY_HEAD",
           T."FPF_DATE",
           T."FPL_DATE",
           T."CH_RECO",
           T."POSTED",
           T."REG_TRANTYPE",
           T."CROR_PLANNO",
           T."CROR_DATE",
           T."AUDIT_FPDATE",
           T."PLAN_TYPE",
           T."REG_SUBBROK",
           T."SEQ_NO",
           T."REG_TRAN_FLAG",
           T."AUM_FLAG",
           T."INV_NAME",
           T."PORTFOLIO_FLAG",
           T."DUP_FLAG",
           T."DUP_FLAG1",
           T."DUP_FLAG2",
           T."UNIQUE_ID",
           T."AUTOMAP_FLAG",
           T."FP_STATUS",
           T."MODIFY_TALISMA",
           T."TRAN_SRC",
           T."REMARKS_1",
           T."AMOUNT1",
           NT.TRAN_CODE                            AS TRANCODE,
           NT.AMOUNT1                              AS AMT1,
           NT.AMOUNT2,
           NT.REG_CHARGE,
           NT.SERVICETAX,
           NT.TRAN_CHARGE,
           B.BRANCH_CODE                           AS BCODE,
           B.BRANCH_NAME,
           R.REGION_ID,
           R.REGION_NAME,
           Z.ZONE_ID,
           Z.ZONE_NAME,
           B.NSDL_NO,
           OP.OSCH_NAME,
           I.INVESTOR_NAME,
           E.RM_NAME,
           E.PAYROLL_ID,
           RE.REQUEST_NAME,
           (SELECT BRANCH_NAME     AS POPBRANCH
              FROM BRANCH_MASTER
             WHERE NSDL_NO = T.FOLIO_NO)           POPBRANCH,
           (SELECT BRANCH_NAME     AS SUBBRANCH
              FROM BRANCH_MASTER
             WHERE BRANCH_CODE = I.BRANCH_CODE)    SUBBRANCH,
           T.INVOICE_NO
      FROM TRANSACTION_ST   T,
           NPS_TRANSACTION  NT,
           BRANCH_MASTER    B,
           REGION_MASTER    R,
           ZONE_MASTER      Z,
           OTHER_PRODUCT    OP,
           INVESTOR_MASTER  I,
           EMPLOYEE_MASTER  E,
           REQUEST_MASTER   RE
     WHERE     T.TRAN_CODE = NT.TRAN_CODE
           AND T.BUSI_BRANCH_CODE = B.BRANCH_CODE
           AND B.REGION_ID = R.REGION_ID
           AND B.ZONE_ID = Z.ZONE_ID
           AND T.SCH_CODE = OP.OSCH_CODE
           AND T.CLIENT_CODE = I.INV_CODE
           AND T.RMCODE = E.RM_CODE
           AND T.APP_NO = RE.REQUEST_CODE;
