CREATE OR REPLACE PROCEDURE WEALTHMAKER.PSM_MC_RTA_BY_TR ( 
  P_AR_NO   VARCHAR2,   
  P_CURSOR  OUT SYS_REFCURSOR
)
AS
    VSQL CLOB;
    VTRANCODE VARCHAR2(50);
BEGIN
    
/* db targate 
DBLINK
UAT: WEALTHMAKER_MF.transaction_st tmf
LIVE: transaction_st@MF.BAJAJCAPITAL tmf

*/
  
    SELECT RTA_TRAN_CODE INTO VTRANCODE FROM TRANSACTION_MF_TEMP1 WHERE TRAN_CODE=P_AR_NO;  
      
    VSQL := 'SELECT   FOLIO_NO, SCH_CODE, TR_DATE, TRAN_TYPE,MAX (inv_name) Inv_Name, MAX (ADDRESS) ADDRESS, MAX (BROKER_CODE) BROKER_CODE, MAX (CITY_NAME) CITY_NAME, max(sch_name)SCH_NAME,MAX(MUT_CODE)MUT_CODE, MAX(MUT_NAME)MUT_NAME, MAX(RM_NAME)RM_NAME, MAX(BRANCH_NAME)BRANCH_NAME, MAX (APP_NO) APP_NO,';
    VSQL := VSQL || ' MAX (CHEQUE_NO) CHEQUE_NO, SUM (AMOUNT) AMOUNT, MAX (BUSI_BRANCH_CODE) BUSI_BRANCH_CODE,MAX (BUSINESS_RMCODE) BUSINESS_RMCODE,GETTRANCODE(FOLIO_NO,SCH_CODE,TR_DATE,TRAN_TYPE)UNIQUE_TRAN FROM (SELECT  TRAN_TYPE,T.INV_NAME,(i.ADDRESS1||'',''||i.ADDRESS2||'',''||i.EMAIL) ADDRESS, REG_SUBBROK BROKER_CODE,C.CITY_NAME, ';              
    VSQL := VSQL || ' T.SCH_CODE,SCH_NAME SCH_NAME,T.MUT_CODE,AMC.MUT_NAME MUT_NAME, RM_NAME,BRANCH_NAME,APP_NO,FOLIO_NO, CHEQUE_NO,AMOUNT,  T.TRAN_CODE,REG_DATE AS TR_DATE,BUSI_BRANCH_CODE, BUSINESS_RMCODE FROM EMPLOYEE_MASTER E, BRANCH_MASTER B,MUT_FUND AMC,SCHEME_INFO SCH, transaction_st@MF.BAJAJCAPITAL T,INVESTOR_MASTER I,CITY_MASTER C ';
    VSQL := VSQL || ' WHERE I.CITY_ID=C.CITY_ID(+) AND T.CLIENT_CODE = I.INV_CODE AND TO_CHAR(T.RMCODE) = E.RM_CODE AND t.BRANCH_CODE = B.BRANCH_CODE AND T.MUT_CODE = AMC.MUT_CODE AND T.SCH_CODE = SCH.SCH_CODE AND (DUP_FLAG2 = 0 OR (REG_TRAN_TYPE=''TICOB'' AND DUP_FLAG2 IN(0,9)))';
    IF P_AR_NO IS NOT NULL THEN
        VSQL := VSQL || ' AND T.TRAN_CODE IN( '''|| VTRANCODE ||''')';  
    END IF;
    
    VSQL := VSQL || ' AND (T.ASA <> ''C'' OR T.ASA IS NULL) AND T.TRAN_TYPE IN (''PURCHASE'', ''REINVESTMENT'',''SWITCH IN'') ORDER BY  TR_DATE,RM_NAME) GROUP BY FOLIO_NO,SCH_CODE,TR_DATE,TRAN_TYPE ';
    
    --OPEN P_CURSOR FOR select VSQL from dual;
    --OPEN P_CURSOR FOR VSQL ;
    open p_cursor for SELECT * FROM TRANSACTION_MF_TEMP1 WHERE TRAN_CODE=P_AR_NO; 
        
EXCEPTION
    WHEN OTHERS
    THEN RAISE ; 
     
END;
/
