CREATE OR REPLACE PROCEDURE WEALTHMAKER.PSM_MC_UNRECO( 
  P_TRAN_CODE       IN VARCHAR2,
  P_RTA_TRAN_CODE   IN VARCHAR2,
  P_ERRORMESSAGE    OUT VARCHAR2,
  P_CURSOR OUT SYS_REFCURSOR 
)
AS
BEGIN
      P_ERRORMESSAGE := NULL;

    BEGIN
        IF P_TRAN_CODE IS NOT NULL AND P_RTA_TRAN_CODE IS NOT NULL  THEN
        
           EXECUTE IMMEDIATE 'UPDATE TRANSACTION_MF_TEMP1 SET REMARK_RECO=NULL,PROCESSED=NULL,AMOUNT=ORIG_AMOUNT, REC_FLAG=NULL,RECO_DATE=NULL,REC_USER=NULL,RTA_TRAN_CODE=NULL WHERE TRAN_CODE='''||P_TRAN_CODE||'''';
           COMMIT;
           EXECUTE IMMEDIATE 'UPDATE TRANSACTION_MF_TEMP1 SET REMARK_RECO=NULL,PROCESSED=NULL,AMOUNT=ORIG_AMOUNT, REC_FLAG=NULL,RECO_DATE=NULL,REC_USER=NULL,RTA_TRAN_CODE=NULL WHERE BASE_TRAN_CODE='''||P_TRAN_CODE||'''';
           COMMIT;
           EXECUTE IMMEDIATE 'UPDATE transaction_st@MF.BAJAJCAPITAL SET REC_FLAG=NULL,HO_TRAN_CODE=NULL WHERE TRAN_CODE IN('''||P_RTA_TRAN_CODE||''')';
           COMMIT;
        ELSE
            P_ERRORMESSAGE := 'AR NOT AVALABLE';
        END IF;
    EXCEPTION
        WHEN OTHERS
        THEN
            P_ERRORMESSAGE := SQLERRM (SQLCODE);

           
    END;
     OPEN P_CURSOR FOR SELECT '' || P_ERRORMESSAGE || '' FROM DUAL;

END;
/
