CREATE OR REPLACE PROCEDURE WEALTHMAKER.PSM_MC_AUDIT_TR (  
  P_AR_NO           IN  VARCHAR2,  
  P_ERRORMESSAGE    OUT VARCHAR2,
  P_CURSOR OUT SYS_REFCURSOR
)
AS
BEGIN
    
    P_ERRORMESSAGE := NULL;

    BEGIN
        IF P_AR_NO IS NOT NULL THEN
           EXECUTE IMMEDIATE 'UPDATE TRANSACTION_MF_TEMP1 SET AUDIT_FLAG=''Y'' WHERE TRAN_CODE='''||P_AR_NO||'''';
           COMMIT;
        ELSE
            P_ERRORMESSAGE := 'AR NOT AVALABLE';
        END IF;
    EXCEPTION
        WHEN OTHERS THEN
            P_ERRORMESSAGE := SQLERRM (SQLCODE);           
    END;
    
    OPEN P_CURSOR FOR SELECT '' ||  P_ERRORMESSAGE || '' FROM DUAL;
END;

