CREATE OR REPLACE PROCEDURE WEALTHMAKER.PSM_GET_CITY_LIST(
    P_CURSOR OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN P_CURSOR FOR
    SELECT CITY_ID, CITY_NAME
    FROM CITY_MASTER
    WHERE TRIM(DEL_FLAG) IS NULL  
    ORDER BY CITY_NAME;
END PSM_GET_CITY_LIST;
/
