#region All print letter fields value
string arBranchCode   = row["ar_branch_cd"]?.ToString() ?? "N/A";
string companyCode    = row["company_cd"]?.ToString() ?? "N/A";
string clientName     = row["client_name"]?.ToString() ?? "N/A";
string address1       = row["address1"]?.ToString() ?? "N/A";
string address2       = row["address2"]?.ToString() ?? "N/A";
string clAdd3         = row["cl_add3"]?.ToString() ?? "N/A";
string clAdd4         = row["cl_add4"]?.ToString() ?? "N/A";
string clAdd5         = row["cl_add5"]?.ToString() ?? "N/A";
string phone1         = row["cl_phone1"]?.ToString() ?? "N/A";
string phone2         = row["cl_phone2"]?.ToString() ?? "N/A";
string cityName       = row["city_name"]?.ToString() ?? "N/A";
string dueDateBase    = row["due_date"]?.ToString() ?? "01/01/1900"; // Default date value
string remFlag        = row["rem_flage"]?.ToString() ?? "0";         // Default to "0"
string stateName      = row["State_Name"]?.ToString() ?? "N/A";
string companyName    = row["Company_Name"]?.ToString() ?? "N/A";
string favourName     = row["Favour_Name"]?.ToString() ?? "N/A";
string branchName     = row["Branch_Name"]?.ToString() ?? "N/A";
string branchAdd1     = row["Branch_Add1"]?.ToString() ?? "N/A";
string branchAdd2     = row["Branch_Add2"]?.ToString() ?? "N/A";
string planName1      = row["Plan_Name1"]?.ToString() ?? "N/A";
string payMode        = row["Pay_Mode"]?.ToString() ?? "N/A";
string policyNo       = row["Policy_No"]?.ToString() ?? "N/A";
string pName          = row["P_Name"]?.ToString() ?? "N/A";
string iName          = row["I_Name"]?.ToString() ?? "N/A";
string premFreq       = row["prem_freq"]?.ToString() ?? "N/A";
string bPremFreq      = row["bprem_freq"]?.ToString() ?? "N/A";
string planName       = row["plan_name"]?.ToString() ?? "N/A";
string sa             = row["sa"]?.ToString() ?? "0";                // Default to "0"
string premAmt        = row["prem_amt"]?.ToString() ?? "0";          // Default to "0"
string monNo          = row["mon_no"]?.ToString() ?? "0";
string yearNo         = row["year_no"]?.ToString() ?? "0";
string clPin          = row["cl_pin"]?.ToString() ?? "N/A";
string pin1           = row["pin1"]?.ToString() ?? "N/A";
string invCode        = row["inv_code"]?.ToString() ?? "N/A";
string invCode1       = row["inv_code1"]?.ToString() ?? "N/A";
string importDataType = row["importdatatype"]?.ToString() ?? "N/A";
string dueDate        = GetDateFromDateTimeString(dueDateBase ?? "01/01/1900"); // Handle empty date
#endregion
