Name              Null? Type          
----------------- ----- ------------- 
COMPANY_CD              VARCHAR2(10)  
POLICY_NO               VARCHAR2(30)  
PLAN_NO                 NUMBER(5)     
P_NAME                  VARCHAR2(50)  
I_NAME                  VARCHAR2(50)  
N_NAME                  VARCHAR2(50)  
DOC                     DATE          
LOGIN_DT                DATE          
ISSUED_DT               DATE          
PREM_AMT                NUMBER(14,2)  
SA                      NUMBER(14,2)  
PREM_TERM               NUMBER(3)     
PREM_FREQ               NUMBER(2)     
LAST_STATUS             VARCHAR2(10)  
STATUS_DT               DATE          
PLY_TERM                NUMBER(3)     
FRESH_RENEWAL           NUMBER(3)     
NEXT_RENEWAL_DT_S       DATE          
CLIENT_CD               NUMBER(13)    
ADD1                    VARCHAR2(200) 
ADD2                    VARCHAR2(200) 
ADD3                    VARCHAR2(200) 
ADD4                    VARCHAR2(200) 
PHONE1                  VARCHAR2(50)  
PHONE2                  VARCHAR2(50)  
MOBILE                  VARCHAR2(50)  
CITY_NAME               VARCHAR2(60)  
PAYMENT_MODE            VARCHAR2(15)  
PIN                     VARCHAR2(10)  
NEXT_RENEWAL_DT_M       DATE          
LAST_RENEWAL_DUE        DATE          
LAST_RENEWAL_PAID       DATE          
FLAG                    VARCHAR2(5)   
USER_ID                 VARCHAR2(10)  
BRANCH_CD               NUMBER(8)     
P_DOB                   DATE          
I_DOB                   DATE          
N_DOB                   DATE          
P_OCC_CD                NUMBER(2)     
I_OCC_CD                NUMBER(2)     
N_OCC_CD                NUMBER(2)     
SUB_STATUS              VARCHAR2(10)  
RENEWAL_YEAR            NUMBER(5)     
MARGIN                  NUMBER(12,2)  
LAPSE_FLAG              VARCHAR2(5)   
RESTFORMHEAD            VARCHAR2(5)   
PLAN_NAME               VARCHAR2(60)  
UPDATE_PROG             VARCHAR2(100) 
UPDATE_USER             VARCHAR2(10)  
UPDATE_DATE             DATE          
TEMPFLAG                VARCHAR2(10)  
NEW_INSERT              VARCHAR2(20)  
INSERT_DATE             DATE          
UPDATED_BY              VARCHAR2(10)  
FILE_NAME               VARCHAR2(100) 
COMP_CL_ADD1            VARCHAR2(200) 
COMP_CL_ADD2            VARCHAR2(200) 
COMP_CL_ADD3            VARCHAR2(200) 
COMP_CL_CITY            VARCHAR2(100) 
COMP_CL_PIN             VARCHAR2(70)  
COMP_CL_PHONE1          VARCHAR2(80)  
COMP_CL_PHONE2          VARCHAR2(80)  
COMP_CL_MOBILE          VARCHAR2(50)  
POLICY_FLAG             VARCHAR2(20)  
GROSS_PREM_AMT          NUMBER(14,2)  
BASE_UPDATE             VARCHAR2(1)   
TIMEST                  DATE          
