Name             Null? Type           
---------------- ----- -------------- 
SEQ                    NUMBER(15)     
SYS_AR_NO              NUMBER(12)     
STATUS_DT              DATE           
STATUS_CD              VARCHAR2(1)    
REASON_CD              VARCHAR2(5)    
REMARKS                VARCHAR2(1000) 
NEXT_ACTION_DT         DATE           
NEXT_ACTION            VARCHAR2(100)  
HO                     VARCHAR2(1)    
SYS_AR_DT              DATE           
USERID                 VARCHAR2(50)   
STATUS_UPDATE_ON       DATE           
REMARKS1               VARCHAR2(100)  
STATUS_CD_REN          VARCHAR2(5)    
