SELECT BM.BRANCH_NAME AS BRANCH_NAME , BM.BRANCH_CODE AS BRANCH_CODE, em.rm_name AS RM_NAME, em.rm_code AS RM_CODE, em.source RM_BRANCH
FROM BRANCH_MASTER BM
LEFT JOIN EMPLOYEE_MASTER EM ON em.source = bm.branch_code
INNER JOIN USERDETAILS_JI UD ON BM.BRANCH_CODE = UD.BRANCH_ID
WHERE UD.LOGIN_ID = '38387'
AND UD.ROLE_ID = '261'
ORDER BY BM.BRANCH_NAME;
