Private Sub Get_Comp_TextFilePath(companyname As String)
If companyname = UCase("ALL INSURANCE CO. (SERVICE)") Then
    TxtFile_Name = "FieldParametersALL1_Comm.txt"
ElseIf companyname = UCase("AEGON RELIGARE LIFE INSURANCE") Then
    TxtFile_Name = "FieldParametersAEGON_comm.txt"
ElseIf companyname = UCase("METLIFE INSURANCE COMPANY") Then
    TxtFile_Name = "FieldParametersMET_comm.txt"
ElseIf companyname = UCase("AVIVA LIFE INSURANCE CO. LTD") Then
    TxtFile_Name = "FieldParametersAVIVA1_comm.txt"
ElseIf companyname = UCase("BAJAJ ALLIANZ GENERAL INURANCE") Then
    TxtFile_Name = "FieldParametersBAGI1.txt"
ElseIf companyname = UCase("BAJAJ ALLIANZ LIFE INURANCE CO. LTD.") Then
    TxtFile_Name = "FieldParametersBAJAJ1_Comm.txt"
ElseIf companyname = UCase("BHARTI AXA") Then
    TxtFile_Name = "FieldParametersBHTA1_Comm.txt"
ElseIf companyname = UCase("BIRLA SUN LIFE INSURANCE CO. LTD.") Then
    TxtFile_Name = "FieldParametersBIRLA1_Comm.txt"
ElseIf companyname = UCase("CHOLAMANDALAM MS GENERAL INSURALCE CO.LTD.") Then
    TxtFile_Name = "FieldParametersMSCHOLA1.txt"
ElseIf companyname = UCase("HDFC CHUB GENERAL INSURANCE CO.LTD.") Then
    TxtFile_Name = "FieldParametersHDFCCHUBB1.txt"
ElseIf companyname = UCase("HDFC STANDARD LIFE INSURANCE CO. LTD") Then
    TxtFile_Name = "FieldParametersHDFC1_Comm.txt"
ElseIf companyname = UCase("ICICI Lombard General Insurance  LTD") Then
    TxtFile_Name = "FieldParametersICICIL1.txt"
ElseIf companyname = UCase("ICICI PRUDENTIAL LIFE INSURANCE CO. LTD") Then
    TxtFile_Name = "FieldParametersICICI1_Comm.txt"
ElseIf companyname = UCase("IFFCO-TOKIO GENERAL INSURANCE CO.LTD.") Then
    TxtFile_Name = "FieldParametersITGI1.txt"
ElseIf companyname = UCase("ING Vysaya Life Insurance") Then
    TxtFile_Name = "FieldParametersINGVYS1_Comm.txt"
ElseIf companyname = UCase("LIFE INSURANCE CORPORATION") Then
    TxtFile_Name = "FieldParametersLIC11_Comm.txt"
ElseIf companyname = UCase("MAX NEW YORK LIFE INSURANCE CO. LTD.") Then
    TxtFile_Name = "FieldParametersMNYL1_Comm.txt"
ElseIf companyname = UCase("NATIONAL INSURANCE COMPANY LTD") Then
    TxtFile_Name = "FieldParametersNIC1_Comm.txt"
ElseIf companyname = UCase("NEW INDIA ASSURANCE CO. LTD.") Then
    TxtFile_Name = "FieldParametersNIAC1_COmm.txt"
ElseIf companyname = UCase("KOTAK LIFE INSURANCE CO. LTD.") Then
    TxtFile_Name = "FieldParametersKOTAK1_Comm.txt"
ElseIf companyname = UCase("ORIENTAL INSURANCE CO. LTD") Then
    TxtFile_Name = "FieldParametersOIC1_Comm.txt"
ElseIf companyname = UCase("RELIANCE LIFE INSURANCE CO. LTD.") Then
    TxtFile_Name = "FieldParametersRELLIFE1_Comm.txt"
ElseIf companyname = UCase("RELIENCE GENERAL INSURANCE CO. LTD.") Then
    TxtFile_Name = "FieldParametersRELGEN1_Comm.txt"
ElseIf companyname = UCase("ROYAL SUNDARAM ALLIANCE INSURANCE CO.LTD.") Then
    TxtFile_Name = "FieldParametersRSA1_Comm.txt"
ElseIf companyname = UCase("SBI LIFE INSURANCE") Then
    TxtFile_Name = "FieldParametersSBI1_Comm.txt"
ElseIf companyname = UCase("STAR HEALTH") Then
    TxtFile_Name = "FieldParameters5501_Comm.txt"
ElseIf companyname = UCase("TATA AIG GENERAL INSURANCE CO.LTD.") Then
    TxtFile_Name = "FieldParametersTATAAIG1.txt"
ElseIf companyname = UCase("TATA-AIG LIFE INSURANCE CO. LTD") Then
    TxtFile_Name = "FieldParametersTATA1_Comm.txt"
ElseIf companyname = UCase("UNITED INDIA INSURANCE CO. LTD") Then
    TxtFile_Name = "FieldParametersUIIC1_Comm.txt"
    '------------------mayank gi status update-------------------'
ElseIf OptGeneral.Value = True Then
    TxtFile_Name = "FieldParametersGIBHARTI_Comm.txt"
ElseIf OptNPS.Value = True Then
    TxtFile_Name = "FieldParametersNPS.txt"
End If
End Sub