DROP TRIGGER WEALTHMAKER.TRGBAJAJDUEDATA1;

CREATE OR REPLACE TRIGGER WEALTHMAKER.TRGBAJAJDUEDATA1 AFTER UPDATE ON "WEALTHMAKER"."BAJAJ_DUE_DATA" FOR EACH ROW
DECLARE
LAST_USER VARCHAR2(20);
LAST_DATE DATE;
BEGIN
    IF NVL(:NEW.STATUS_CD,'#')<>NVL(:OLD.STATUS_CD,'#') THEN
        INSERT INTO BAJAJ_DUE_DATA_HIST(POLICY_NO,COMPANY_CD,MON_NO,YEAR_NO,CHANGED_FIELD,PREV_VALUE,CHANGED_VALUE,CURR_UPDATED_USER) 
                VALUES (:NEW.POLICY_NO,:NEW.COMPANY_CD,:NEW.MON_NO,:NEW.YEAR_NO,'STATUS_CD',:OLD.STATUS_CD,:NEW.STATUS_CD,:NEW.LAST_UPDATE);
    END IF;
    IF NVL(:NEW.IMPORTDATATYPE,'#')<>NVL(:OLD.IMPORTDATATYPE,'#') THEN
        INSERT INTO BAJAJ_DUE_DATA_HIST(POLICY_NO,COMPANY_CD,MON_NO,YEAR_NO,CHANGED_FIELD,PREV_VALUE,CHANGED_VALUE,CURR_UPDATED_USER) 
                VALUES (:NEW.POLICY_NO,:NEW.COMPANY_CD,:NEW.MON_NO,:NEW.YEAR_NO,'IMPORTDATATYPE',:OLD.IMPORTDATATYPE,:NEW.IMPORTDATATYPE,:NEW.LAST_UPDATE);
    END IF;
    IF NVL(:NEW.PAY_MODE,'#')<>NVL(:OLD.PAY_MODE,'#') THEN
        INSERT INTO BAJAJ_DUE_DATA_HIST(POLICY_NO,COMPANY_CD,MON_NO,YEAR_NO,CHANGED_FIELD,PREV_VALUE,CHANGED_VALUE,CURR_UPDATED_USER) 
                VALUES (:NEW.POLICY_NO,:NEW.COMPANY_CD,:NEW.MON_NO,:NEW.YEAR_NO,'PAY_MODE',:OLD.PAY_MODE,:NEW.PAY_MODE,:NEW.LAST_UPDATE);
    END IF;
    IF NVL(:NEW.PREM_FREQ,'#')<>NVL(:OLD.PREM_FREQ,'#') THEN
        INSERT INTO BAJAJ_DUE_DATA_HIST(POLICY_NO,COMPANY_CD,MON_NO,YEAR_NO,CHANGED_FIELD,PREV_VALUE,CHANGED_VALUE,CURR_UPDATED_USER) 
                VALUES (:NEW.POLICY_NO,:NEW.COMPANY_CD,:NEW.MON_NO,:NEW.YEAR_NO,'PREM_FREQ',:OLD.PREM_FREQ,:NEW.PREM_FREQ,:NEW.LAST_UPDATE);
    END IF;
END ;
/
