CREATE OR REPLACE VIEW VW_PSM_PROCEDURE_LOG AS
SELECT 
    PROCEDURE_NAME,
    STATUS,
    START_TIME,
    END_TIME,
    ROUND((END_TIME - START_TIME)*24*60, 2) AS DURATION_MINUTES,
    RECORD_COUNT,
    MESSAGE,
    ERROR_CODE
FROM PSM_PROCEDURE_LOG
ORDER BY START_TIME DESC;