CREATE OR REPLACE PROCEDURE PSM_PURGE_PROCEDURE_LOGS(
    P_RETENTION_DAYS NUMBER DEFAULT 90
) AS
BEGIN
    DELETE FROM PSM_PROCEDURE_LOG
    WHERE START_TIME < SYSDATE - P_RETENTION_DAYS;
    COMMIT;
END;