create or replace PROCEDURE PSM_EMP_M__GET_CITY (
    P_CURSOR OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN P_CURSOR FOR 
    SELECT CITY_ID, CITY_NAME
    FROM CITY_MASTER
    WHERE CITY_ID IS NOT NULL
    AND STATE_ID IS NOT NULL
    AND DEL_FLAG IS NULL 
    ORDER BY CITY_NAME;
END;