create or replace PROCEDURE PSM_AO_GET_RELATIONSHIPLIST
(
    p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_cursor FOR
    SELECT RELATION_ID, RELATION_NAME
    FROM relationship_master
    WHERE TRIM(RELATION_NAME) IS NOT NULL 
    AND TRIM(relation_id) IS NOT NULL
    ORDER BY RELATION_NAME;

END PSM_AO_GET_RELATIONSHIPLIST;