create or replace PROCEDURE PSM_GET_CLIENT_LIST_BY_CRITERIA (
    P_BRANCH_ID IN VARCHAR2,
    P_MOBILE IN VARCHAR2,
    P_CITY_ID IN VARCHAR2,
    P_PHONE IN VARCHAR2,
    P_CLIENT_CODE IN VARCHAR2,
    P_BUSINESS_CD IN VARCHAR2,
    P_CLIENT_NAME IN VARCHAR2,
    P_CLIENT_LIST OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN P_CLIENT_LIST FOR
    SELECT *
    FROM CLIENT_TEST
   WHERE 
   (UPPER(BRANCH_CODE) = UPPER(P_BRANCH_ID) OR P_BRANCH_ID IS NULL)
  AND (UPPER(MOBILE_NO) = UPPER(P_MOBILE) OR P_MOBILE IS NULL)
  AND (UPPER(CITY_ID) = UPPER(P_CITY_ID) OR P_CITY_ID IS NULL)
  AND (UPPER(TEL2) = UPPER(P_PHONE) OR P_PHONE IS NULL)
  AND (UPPER(CLIENT_CODE) = UPPER(P_CLIENT_CODE) OR P_CLIENT_CODE IS NULL)
  AND (UPPER(CLIENT_PAN) = UPPER(P_BUSINESS_CD) OR P_BUSINESS_CD IS NULL)
  AND (UPPER(CLIENT_NAME) LIKE '%' || UPPER(P_CLIENT_NAME) || '%' OR P_CLIENT_NAME IS NULL)
  AND UPPER(CLIENT_CODE) = UPPER(MAIN_CODE)
  AND ROWNUM < 200
ORDER BY UPPER(CLIENT_NAME);

END;