create or replace PROCEDURE PSM_MPN_GET_COMPANY_MASTER (
    P_CURSOR OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN P_CURSOR FOR
        SELECT COMPANY_NAME, COMPANY_CD
        FROM BAJAJ_COMPANY_MASTER
        ORDER BY COMPANY_NAME;
END PSM_MPN_GET_COMPANY_MASTER;

