Name              Null?    Type         
----------------- -------- ------------ 
STATE_ID          NOT NULL NUMBER(3)    
STATE_NAME                 VARCHAR2(50) 
LOGGEDUSERID               VARCHAR2(10) 
TIMEST                     DATE         
ZONE_ID                    VARCHAR2(3)  
COUNTRY_ID                 NUMBER(5)    
DEL_FLAG                   VARCHAR2(5)  
NPS_STATE_ID               VARCHAR2(4)  
GST_STATE_TYPE             VARCHAR2(6)  
GST_STATE_CODE             VARCHAR2(10) 
GST_ARN_NO                 VARCHAR2(10) 
GSTIN                      VARCHAR2(50) 
STATE_CD                   VARCHAR2(3)  
STATE_COST_CENTER          VARCHAR2(8)  
NAVISION_CODE              VARCHAR2(10) 
GL_NAME                    VARCHAR2(40) 
VENDOR_CODE                VARCHAR2(10) 
VENDOR_NAME                VARCHAR2(40) 
