Name                       Null?    Type           
-------------------------- -------- -------------- 
SYS_AR_NO                  NOT NULL NUMBER(12)     
SYS_AR_DT                           DATE           
AR_NO                               NUMBER(12)     
AR_DT                               DATE           
BRANCH_CD                           NUMBER(8)      
EMP_NO                              NUMBER(12)     
REF_EMP_NO                          NUMBER(12)     
CLIENT_CD                           VARCHAR2(13)   
APP_NO                              VARCHAR2(40)   
APP_DT                              DATE           
P_NAME                              VARCHAR2(55)   
I_NAME                              VARCHAR2(55)   
N_NAME                              VARCHAR2(55)   
P_DOB                               DATE           
I_DOB                               DATE           
N_DOB                               DATE           
P_OCC_CD                            NUMBER(2)      
I_OCC_CD                            NUMBER(2)      
N_OCC_CD                            NUMBER(2)      
RELATION_CD                         NUMBER(2)      
ADD1                                VARCHAR2(500)  
ADD2                                VARCHAR2(500)  
CITY                                VARCHAR2(40)   
STATE_CD                            NUMBER(5)      
PIN                                 VARCHAR2(12)   
IADD1                               VARCHAR2(200)  
IADD2                               VARCHAR2(100)  
ICITY                               VARCHAR2(40)   
ISTATE_CD                           NUMBER(5)      
IPIN                                VARCHAR2(12)   
STD_RESI                            VARCHAR2(8)    
PHONE_RESI                          VARCHAR2(50)   
STD_OFF                             VARCHAR2(8)    
PHONE_OFF                           VARCHAR2(30)   
MOBILE                              VARCHAR2(30)   
EMAIL                               VARCHAR2(60)   
COMPANY_CD                          VARCHAR2(10)   
PLAN_NO                             NUMBER(6)      
SA                                  NUMBER(14,2)   
PLY_TERM                            NUMBER(3)      
PREM_TERM                           NUMBER(3)      
PREM_FREQ                           NUMBER(2)      
PREM_AMT                            NUMBER(14,2)   
RIDER_PREM                          NUMBER(14,2)   
XRT                                 NUMBER(14,2)   
TOTAL_PREM                          NUMBER(14,2)   
ANUAL_PREM                          NUMBER(14,2)   
BACK_PREM                           NUMBER(14,2)   
EXPENSE                             NUMBER(14,2)   
WT_PREM                             NUMBER(14,2)   
WT_ANUAL_PREM                       NUMBER(14,2)   
PAYMENT_MODE                        VARCHAR2(20)   
CHQ_NO                              VARCHAR2(50)   
CHQ_DT                              DATE           
BANK_BRANCH                         VARCHAR2(45)   
FRESH_RENEWAL                       NUMBER(2)      
POLICY_NO                           VARCHAR2(45)   
LOGIN_DT                            DATE           
DOC                                 DATE           
PLY_ISSUE_DT                        DATE           
NEXT_DUE_DT                         DATE           
NEXT_ACTION_DT                      DATE           
STATUS_CD                           VARCHAR2(2)    
USERID                              VARCHAR2(50)   
ENTRY_DT                            DATE           
COMM                                NUMBER(14,2)   
HO                                  VARCHAR2(1)    
BRANCH_CLIENT_CD                    VARCHAR2(10)   
BRANCH_SYS_AR_NO                    NUMBER(12)     
MANAGER_NO                          NUMBER(12)     
PTYPE                               VARCHAR2(5)    
REMARKS                             VARCHAR2(255)  
FINANCE_PLAN                        CHAR(1)        
REC_FLAG                            VARCHAR2(1)    
RECO_MMYYYY                         DATE           
REMARKRECO                          VARCHAR2(1000) 
COMM_RECEIVE                        NUMBER(10)     
OPE_RECEIVE                         NUMBER(10,2)   
RECO_CAN_DATE                       DATE           
HISTORY_FLAG                        VARCHAR2(5)    
DIRECT_SALE                         VARCHAR2(10)   
LAST_UPDATE                         DATE           
MODIFIED_USER                       VARCHAR2(10)   
FPF_DATE                            DATE           
FAMILY_HEAD                         NUMBER(13)     
FPL_DATE                            DATE           
GROSS_PREM                          NUMBER(16,2)   
VOUCHER_NO                          NUMBER(10)     
INTENDED_PREM                       NUMBER(3)      
CHEQ_AMT                            NUMBER(16,2)   
CROR_PLANNO                         VARCHAR2(200)  
PLAN_TYPE                           VARCHAR2(50)   
SIP_ADV_FLAG                        CHAR(1)        
MODAL_PREM                          CHAR(1)        
BEF_PREM_AMT                        NUMBER(14,2)   
TD_ID                               NUMBER(5)      
CHQ_DEP_DATE                        DATE           
GUEST_CD                            VARCHAR2(12)   
PITCH_BOOK_NO                       VARCHAR2(20)   
AUDIT_FPDATE                        DATE           
MATCHED_CD                          VARCHAR2(20)   
LAST_UPDATE_DT                      DATE           
MATCHED_COMM_CD                     VARCHAR2(20)   
RECO_USER                           VARCHAR2(30)   
RECO_DATE                           DATE           
VERIFY_AR                           NUMBER(1)      
P_CODE                              VARCHAR2(15)   
N_CODE                              VARCHAR2(15)   
VERIFY_USER                         VARCHAR2(10)   
VERIFY_DT                           DATE           
LAPSED_FLAG                         VARCHAR2(1)    
NR_FLAG                             VARCHAR2(2)    
NR_DATE                             DATE           
I_NAME1                             VARCHAR2(55)   
P_NAME1                             VARCHAR2(55)   
FP_STATUS                           CHAR(1)        
MANUF_ID                            NUMBER         
MODEL_ID                            NUMBER         
VARIENT_ID                          NUMBER         
MODEL_NAME                          VARCHAR2(30)   
VARIENT_NAME                        VARCHAR2(40)   
MANUF_YEAR                          NUMBER         
EXPENSE_NEW                         NUMBER         
MODIFY_TALISMA                      DATE           
STATUS_CD_REN                       VARCHAR2(50)   
MODIFY_COMM_USER                    VARCHAR2(10)   
LAST_UPDATE_COMM                    DATE           
LAST_UPDATE_DT_COMM                 DATE           
REC_COMM_FLAG                       VARCHAR2(2)    
COMM_AMT                            NUMBER(14,2)   
TRAN_SRC                            VARCHAR2(10)   
REMARKRECO1                         VARCHAR2(50)   
MATCHED_CD1                         VARCHAR2(20)   
MODIFIED_USER1                      VARCHAR2(10)   
LAST_UPDATE1                        DATE           
LAST_UPDATE_DT1                     DATE           
REC_FLAG1                           VARCHAR2(1)    
REMARKS1                            VARCHAR2(100)  
OLD_POLICY_NO                       VARCHAR2(50)   
ANARENEW                            VARCHAR2(2)    
OD_SLAB                             NUMBER(5)      
AUTO_RECO                           DATE           
TRAN_TYPE                           VARCHAR2(15)   
REGISTRATION_DATE                   DATE           
FAMILY_DOC                          VARCHAR2(20)   
DISEASE                             VARCHAR2(20)   
MATERNITY_COVER                     VARCHAR2(6)    
DISEASE_COVER                       VARCHAR2(6)    
CON1                                VARCHAR2(100)  
CON2                                VARCHAR2(100)  
CON3                                VARCHAR2(100)  
AMOUNT_CLAIMED                      NUMBER(16,2)   
PROPOSAL_FORMNO                     NUMBER(10)     
PRE_POLICY_NO                       VARCHAR2(15)   
PERIOD_INSURANCE                    DATE           
INSURER_NAME                        VARCHAR2(50)   
DIV_OFF_NO                          VARCHAR2(20)   
BR_ADD                              VARCHAR2(250)  
CPNAME                              VARCHAR2(25)   
CPNO                                VARCHAR2(20)   
SYS_ENTRY_DT                        DATE           
PDR_NO                              VARCHAR2(20)   
PDR_DATE                            DATE           
PDR_AMT                             NUMBER         
MOBILE2                             NUMBER(12)     
ESA_SA                              NUMBER(20,2)   
ESA_PREMIUM                         NUMBER(20,2)   
REC_DUP_FLAG                        VARCHAR2(5)    
MYRECO_USER                         VARCHAR2(10)   
MYRECO_DATE                         DATE           
AMOUNT_DIFF                         NUMBER(20,2)   
CHASIS_NO                           VARCHAR2(30)   
ENGINE_NO                           VARCHAR2(25)   
GI_RECO                             CHAR(1)        
GI_RECO_DATE                        DATE           
CALL_CENTER_RM                      NUMBER(10)     
CALL_CENTER_BRANCH                  NUMBER(8)      
ACT_SYS_AR_DT                       DATE           
RENEWAL_RECO                        VARCHAR2(20)   
NO_OF_PASSENGER                     NUMBER         
TOTAL_LICENSED_AMT                  NUMBER(12,2)   
TERM                                VARCHAR2(10)   
NOS                                 NUMBER(5)      
FRESH_RENEWAL_MONTH                 NUMBER         
TRAN_SOURCE                         VARCHAR2(2)    
OWNER_DRIVER                        NUMBER(5,2)    
PAID_DRIVER                         NUMBER(5,2)    
UNNAMED_PA                          NUMBER(10,2)   
ISSUED_USER_ID                      VARCHAR2(100)  
ISSUED_USER_DATE                    DATE           
RECO_GI_FLAG                        VARCHAR2(5)    
RECO_GI_USER                        VARCHAR2(10)   
RECO_GI_DATE                        DATE           
GROSS_PREM_AMT                      NUMBER(14,2)   
RENEWAL_PAY                         VARCHAR2(2)    
P_MOBILE                            NUMBER(13)     
BASE_UPD                            VARCHAR2(1)    
PAID_TO_COM                         NUMBER(2)      
APPROVE_NON_ECS                     CHAR(1)        
P_EMAIL                             VARCHAR2(50)   
COLLECTED_RENEWAL_PREM              NUMBER(14,2)   
RENEWAL_STATUS                      VARCHAR2(2)    
PORTABLE_COMPANY_NO                 VARCHAR2(45)   
PORTABLE_POLICY_NO                  VARCHAR2(45)   
TEMPAR_NO                           VARCHAR2(15)   
LAPSED_DATE                         DATE           
LAPSED_MNTHS                        NUMBER(5)      
DOC_ID                              VARCHAR2(50)   
POLICY_DISPATCH_DATE                DATE           
MAP_UNMAP                           VARCHAR2(1)    
REVERSE                             CHAR(1)        
CLIENT_TYPE                         VARCHAR2(50)   
EXPENSE_PER                         NUMBER(20,3)   
INTRO_EXP                           NUMBER(4,2)    
SUPER_ANA_CODE                      NUMBER(10)     
EIAFORM                             VARCHAR2(15)   
IRNAME                              VARCHAR2(10)   
EIAAC                               NUMBER(15)     
POSP_TRAN                           CHAR(1)        
LEAD_ID                             VARCHAR2(50)   
POSP_EXPENSE                        NUMBER(14,2)   
UPD_API                             CHAR(1)        
THIRD_PARTY_PREM                    NUMBER(14,2)   
CONVERSION                          CHAR(1)        
BACKDATED_FLAG                      CHAR(1)        
CON_BCODE                           VARCHAR2(10)   
OD_RATE                             NUMBER(6,4)    
OD_EXPENSE                          NUMBER(14,2)   
TP_RATE                             NUMBER(6,4)    
TP_EXPENSE                          NUMBER(14,2)   
PREMIUM_TYPE_ID                     NUMBER(5)      
PLY_EXPIRYDATE_TP                   DATE           
POLICY_DOCUMENT_TYPE                VARCHAR2(100)  
GST_ODRIVER                         NUMBER(14,2)   
GST_PAIDDRIVER                      NUMBER(14,2)   
GST_UNNAMEDPA                       NUMBER(14,2)   
GST_OD                              NUMBER(14,2)   
GST_TP                              NUMBER(14,2)   
OD_PREM_REST                        NUMBER(14,2)   
IRDA_RM                             VARCHAR2(10)   
IRDA_BRANCH                         VARCHAR2(10)   
PROPOSER_NAME_MISDATA               VARCHAR2(100)  
STATE_ID                            VARCHAR2(150)  
RTO_CODE                            VARCHAR2(500)  
FUEL_ID                             VARCHAR2(50)   
INSURER_VARIANTNAME                 VARCHAR2(100)  
IS_OD_RENEWAL                       CHAR(1)        
FUTURE_MODE                         VARCHAR2(10)   
ISSUPERTOPUP                        CHAR(1)        
DEDUCTIBLE                          NUMBER(14,2)   
PLAN_CATEGORY                       VARCHAR2(10)   
IS_RETIREMENT_PLANNING              CHAR(1)        
ORIG_DOC_ID                         VARCHAR2(20)   
IS_INTERNAL_PORT                    CHAR(1)        
IS_STANDALONE_TP                    CHAR(1)        
TON                                 NUMBER(10,2)   
IS_PRE_RETIREMENT_PLANNING          CHAR(1)        
NONPOSP_EXPENSE                     NUMBER(14,2)   
AGENT_CODE_CHILD                    NUMBER(13)     
NEW_SYS_AR_NO                       NUMBER(12)     
PREM_AMT_TERR                       NUMBER(14,2)   
PET_TYPE_ID                         NUMBER         
BREED_CAT_ID                        NUMBER         
BREED_ID                            NUMBER         
PET_VACC_STATUS                     CHAR(1)        
PET_GENDER                          VARCHAR2(6)    
PET_AGE                             NUMBER         
DISEASES_ID                         NUMBER         
SOURCE                              VARCHAR2(10)   
TOTAL_GROSS_COLLECTION              NUMBER(16,2)   
