CREATE OR REPLACE PROCEDURE PSM_AM_GET_PAYMODEID (
    P_CURSOR OUT SYS_REFCURSOR
) 
IS
BEGIN
    -- Open a cursor 
    OPEN P_CURSOR FOR
    SELECT ITEMSERIALNUMBER, ITEMNAME 
    FROM FIXEDITEM WHERE ITEMTYPE = '10' order by itemname;

END;
