CREATE OR REPLACE PROCEDURE WEALTHMAKER.PSMM_INV_ADD_UP_GET_DATA (
    P_INV_CODE        IN VARCHAR2,
    P_LOGIN           IN VARCHAR2,
    P_ROLE            IN VARCHAR2,
    P_CURSOR          OUT SYS_REFCURSOR
) AS
    V_ERROR             VARCHAR2(4000);
    V_INV_CODE      VARCHAR2(100);
    V_ADD1          VARCHAR2(500);
    V_ADD2          VARCHAR2(500);
    V_CITY_NAME     VARCHAR2(100);
    V_STATE_NAME    VARCHAR2(100);
    V_MOBILE        VARCHAR2(100);
    V_EMAIL         VARCHAR2(100);
    V_PIN           VARCHAR2(100);
    V_PAN           VARCHAR2(100);
    V_AADHAR        VARCHAR2(100);
    V_DOB           VARCHAR2(100);
    V_INV_NAME      VARCHAR2(100);
    V_IS_HEAD       VARCHAR(100);
    V_CITY_ID       VARCHAR2(100);
BEGIN 
    SAVEPOINT SP_FIND;

    SELECT NVL(A.ADDRESS1,' '),NVL(A.ADDRESS2,' '),NVL(B.CITY_NAME,' '),NVL(C.STATE_NAME,' '),NVL(A.MOBILE,0),NVL(A.EMAIL,' '),NVL(A.PINCODE,' '),NVL(UPPER(A.PAN),' '),A.AADHAR_CARD_NO,A.DOB,INVESTOR_NAME, INV_CODE, A.CITY_ID
    INTO V_ADD1, V_ADD2, V_CITY_NAME, V_STATE_NAME, V_MOBILE, V_EMAIL, V_PIN, V_PAN, V_AADHAR, V_DOB, V_INV_NAME, V_INV_CODE, V_CITY_ID
    FROM INVESTOR_MASTER A,CITY_MASTER B, STATE_MASTER C WHERE A.CITY_ID=B.CITY_ID(+) AND B.STATE_ID=C.STATE_ID(+) AND A.INV_CODE=P_INV_CODE;

    SELECT IS_FAMILY_HEAD(P_INV_CODE) INTO V_IS_HEAD FROM DUAL;

    OPEN P_CURSOR FOR 
        SELECT 
        'SUCCESS: Investor Information Found' AS MSG, 
        V_INV_CODE AS V_INV_CODE, 
        V_ADD1 AS V_ADD1, 
        V_ADD2 AS V_ADD2, 
        V_CITY_NAME AS V_CITY_NAME, 
        V_CITY_ID AS V_CITY_ID,
        V_STATE_NAME AS V_STATE_NAME, 
        V_MOBILE AS V_MOBILE, 
        V_EMAIL AS V_EMAIL, 
        V_PIN AS V_PIN, 
        V_PAN AS V_PAN, 
        V_AADHAR AS V_AADHAR, 
        V_DOB AS V_DOB, 
        V_INV_NAME AS V_INV_NAME,
        V_IS_HEAD AS V_IS_HEAD        
        FROM DUAL;

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK TO SP_FIND;
        V_ERROR := 'ERROR:' || SQLERRM ;
        OPEN P_CURSOR FOR SELECT V_ERROR MSG FROM DUAL;
END;
/