SELECT inv_code, INVESTOR_NAME, ADDRESS1, ADDRESS2, EMAIL, DOB, MOBILE, PAN, PINCODE FROM INVESTOR_MASTER 
--WHERE INV_CODE = '41286003001';
WHERE  inv_code NOT LIKE '%' || SUBSTR('41286003001',1,8) || '%';


SELECT INVESTOR_NAME, ADDRESS1, ADDRESS2, EMAIL, DOB, MOBILE, PAN, PINCODE FROM INVESTOR_MASTER WHERE SOURCE_ID = SUBSTR('41286003001',1,8);

SELECT MODIFY_USER, MODIFY_DATE, PAN, MOBILE, EMAIL, ADDRESS1, ADDRESS2, PINCODE, CITY_ID FROM CLIENT_MASTER WHERE CLIENT_CODE = SUBSTR('41286003001',1,8); 


SELECT  MODIFY_USER, MODIFY_DATE, AADHAR_CARD_NO, CLIENT_PAN, MOBILE_NO, EMAIL, ADD1, ADD2, PINCODE FROM CLIENT_TEST WHERE CLIENT_CODEKYC =   SUBSTR('41286003001',1,8); 
SELECT  MODIFY_USER, MODIFY_DATE, AADHAR_CARD_NO, CLIENT_PAN, MOBILE_NO, EMAIL, ADD1, ADD2, PINCODE FROM CLIENT_TEST WHERE SOURCE_CODE =   SUBSTR('41286003001',1,8); 


UPDATE INVESTOR_MASTER
SET --MODIFY_USER = P_LOGIN, 
    MODIFY_DATE = SYSDATE,
    ADDRESS1 = TRIM('P_ADDRESS1'), ADDRESS2 = 'SASD',
    PINCODE = TRIM('123123')
WHERE SOURCE_ID = SUBSTR('41286003001',1,8); COMMIT;




        UPDATE CLIENT_MASTER 
        SET MODIFY_USER = P_LOGIN, MODIFY_DATE = SYSDATE, 
            PAN = TRIM(P_PAN), MOBILE = TRIM(P_MOBILE), 
            EMAIL = TRIM(P_EMAIL), ADDRESS1 = TRIM(P_ADDRESS1), 
            ADDRESS2 = TRIM(P_ADDRESS2), PINCODE = TRIM(P_PINCODE), CITY_ID = P_CITY_ID
        WHERE client_code = SUBSTR(P_INV_CODE,1,8);


SELECT VERIFICATION_FLAG FROM TB_DOC_UPLOAD WHERE  COMMON_ID = '11629684';

UPDATE TB_DOC_UPLOAD SET VERIFICATION_FLAG = '1' WHERE COMMON_ID = '11629684'; COMMIT;



SELECT COMMON_ID,A.BUSI_RM_CODE,A.BUSI_BRANCH_CODE,A.BUSI_TR_DATE,A.SCH_CODE,A.INV_CODE,B.BRANCH_NAME,A.EXPENSE 
FROM TB_DOC_UPLOAD A,BRANCH_MASTER B WHERE A.BUSI_BRANCH_CODE=B.BRANCH_CODE 
AND  TRAN_TYPE='MF' AND VERIFICATION_FLAG='1' AND REJECTION_STATUS='0'  AND PUNCHING_FLAG='0'
AND DOC_UPLOAD_DATE>='01-JUN-2024';


-- 11632841, 11632842, 11632510