Name         Null?    Type          
------------ -------- ------------- 
ACCOUNTNO    NOT NULL NUMBER        
CLCODE                VARCHAR2(10)  
NAME                  VARCHAR2(200) 
MOBILE                VARCHAR2(12)  
EMAIL                 VARCHAR2(100) 
RESIADD1              VARCHAR2(200) 
RESIADD2              VARCHAR2(200) 
CITY                  VARCHAR2(100) 
STATE                 VARCHAR2(100) 
ACCFLAG               VARCHAR2(2)   
MANACCOUNTNO          VARCHAR2(30)  
RESIPINCODE           VARCHAR2(10)  
PANNO                 VARCHAR2(12)  
ONLINEWEB             VARCHAR2(4)   
APPNO                 VARCHAR2(30)  
ENT_DATE              DATE          
CLIENT_CODE           VARCHAR2(10)  
DISTRICT              VARCHAR2(100) 
